# Generated by Django 4.2.3 on 2023-07-22 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("approvement", "0002_procedurestatus_slug_role_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="StepStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("slug", models.SlugField(max_length=250, null=True, unique=True)),
            ],
        ),
    ]
