# Generated by Django 4.2.3 on 2023-07-22 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("approvement", "0003_stepstatus"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="procedurestep",
            name="is_approved",
        ),
        migrations.AddField(
            model_name="procedurestep",
            name="status",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="step",
                to="approvement.stepstatus",
            ),
        ),
    ]
