# Generated by Django 4.2.3 on 2023-07-22 20:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("approvement", "0004_remove_procedurestep_is_approved_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="is_corrected",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="comment",
            name="response_author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="given_response",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="response_text",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
