# Generated by Django 4.2.3 on 2023-07-07 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_short", models.CharField(max_length=45)),
                ("name_full", models.CharField(max_length=120)),
                ("country", models.CharField(max_length=120)),
            ],
            options={
                "ordering": ["name_short"],
            },
        ),
        migrations.CreateModel(
            name="Building",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=5)),
                ("name", models.CharField(max_length=45)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="doc_manager.project",
                    ),
                ),
            ],
            options={
                "ordering": ["code"],
            },
        ),
    ]
