# Generated by Django 4.2.3 on 2023-07-10 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doc_manager", "0002_documentstatus_document"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="code",
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name="document",
            name="date_creation",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="document",
            name="date_update",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
