# Generated by Django 4.2.3 on 2023-07-15 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("doc_manager", "0003_project_code_alter_document_date_creation_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AttachedFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="E:\\PythonProject\\docmandata")),
            ],
        ),
        migrations.AlterField(
            model_name="building",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="buildings",
                to="doc_manager.project",
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="building",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="building",
                to="doc_manager.building",
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="status",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="doc_manager.documentstatus",
            ),
        ),
    ]
